import { IconType } from 'react-icons'
import {
    IoAirplane,
    IoAlarm,
    IoAnalytics,
    IoBagHandle,
    IoHappy,
    IoBalloon,
    IoBarbell,
    IoBeer,
    IoBook,
    IoCafe,
    IoCall,
    IoCart,
    IoFastFood,
    IoCalendarNumber,
    IoGameController,
    IoGift,
    IoPlanet,
    IoServerSharp,
    IoTicket,
    IoWine,
    IoCalculator,
    IoBuild,
    IoBed,
    IoLeaf,
    IoPaw,
    IoMedkit,
    IoMoon,
} from 'react-icons/io5'

const iconList: { [key: string]: IconType } = {
    IoAirplane,
    IoAlarm,
    IoAnalytics,
    IoBagHandle,
    IoHappy,
    IoBalloon,
    IoBarbell,
    IoBeer,
    IoBook,
    IoCafe,
    IoCall,
    IoCart,
    IoFastFood,
    IoCalendarNumber,
    IoGameController,
    IoGift,
    IoPlanet,
    IoServerSharp,
    IoTicket,
    IoWine,
    IoCalculator,
    IoBuild,
    IoBed,
    IoLeaf,
    IoPaw,
    IoMedkit,
    IoMoon,
}

export default iconList
