import { IconType } from 'react-icons'
import {
    IoAirplane,
    IoAlarm,
    IoBagHandle,
    IoHappy,
    IoBarbell,
    IoBeer,
    IoBook,
    IoCart,
    IoFastFood,
    IoCalendarNumber,
    IoGameController,
    IoGift,
    IoBuild,
    IoBed,
    IoLeaf,
    IoPaw,
    IoMedkit,
    IoMoon,
    IoDocuments,
    IoHeart,
    IoPulse,
    IoLaptop,
    IoSchool,
} from 'react-icons/io5'

const iconList: { [key: string]: IconType } = {
    IoAirplane,
    IoAlarm,
    IoBagHandle,
    IoHappy,
    IoBarbell,
    IoBeer,
    IoBook,
    IoCart,
    IoFastFood,
    IoCalendarNumber,
    IoGameController,
    IoGift,
    IoBuild,
    IoBed,
    IoLeaf,
    IoPaw,
    IoMedkit,
    IoMoon,
    IoDocuments,
    IoHeart,
    IoPulse,
    IoLaptop,
    IoSchool,
}

export default iconList
